In [33]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras import Sequential
from keras.layers import Dense, Input,Normalization
from keras.activations import sigmoid
from keras.losses import mean_squared_error,BinaryCrossentropy

# 手动构建

每一层的计算需要人工进行输入

In [34]:
x = np.array([[200,17]])
layer_1 = Dense(3,"sigmoid")
a_1 = layer_1(x)
print(a_1)

tf.Tensor([[1.032576e-19 1.000000e+00 4.880519e-21]], shape=(1, 3), dtype=float32)


In [35]:
layer_2 = Dense(1,"sigmoid")
a_2 = layer_2(a_1)
print(a_2)

tf.Tensor([[0.64396334]], shape=(1, 1), dtype=float32)


# 组合起来，自动执行，只输入一次

构建神经网络

In [36]:
# 第一种
L1 = Dense(3,"sigmoid")
L2 = Dense(1,"sigmoid")
model1 = Sequential([L1,L2])
# 第二种 以列表的形式完成整个神经网络的构建
model2 = Sequential(
    [
        Dense(units=3,activation="sigmoid",name="L1"),
        Dense(units=1,activation="sigmoid",name="L2")
    ]
)
# 第三种 使用.add()
model3 = Sequential()
model3.add(Dense(units=3,activation="sigmoid",name="L1"))
model3.add(Dense(units=1,activation="sigmoid",name="L2"))

创建或者获取数据

In [37]:
path = "ex2data1.txt"
data = pd.read_csv(path,header=None,names=["exam1","exam2","admitted"])
cols = data.shape[1]
x_train = data.iloc[:,0:cols-1]
y_train = data.iloc[:,cols-1:cols]
x = np.array(x_train)
y = np.array(y_train)
print(x)
print(y)

[[34.62365962 78.02469282]
 [30.28671077 43.89499752]
 [35.84740877 72.90219803]
 [60.18259939 86.3085521 ]
 [79.03273605 75.34437644]
 [45.08327748 56.31637178]
 [61.10666454 96.51142588]
 [75.02474557 46.55401354]
 [76.0987867  87.42056972]
 [84.43281996 43.53339331]
 [95.86155507 38.22527806]
 [75.01365839 30.60326323]
 [82.30705337 76.4819633 ]
 [69.36458876 97.71869196]
 [39.53833914 76.03681085]
 [53.97105215 89.20735014]
 [69.07014406 52.74046973]
 [67.94685548 46.67857411]
 [70.66150955 92.92713789]
 [76.97878373 47.57596365]
 [67.37202755 42.83843832]
 [89.67677575 65.79936593]
 [50.53478829 48.85581153]
 [34.21206098 44.2095286 ]
 [77.92409145 68.97235999]
 [62.27101367 69.95445795]
 [80.19018075 44.82162893]
 [93.1143888  38.80067034]
 [61.83020602 50.25610789]
 [38.7858038  64.99568096]
 [61.37928945 72.80788731]
 [85.40451939 57.05198398]
 [52.10797973 63.12762377]
 [52.04540477 69.43286012]
 [40.23689374 71.16774802]
 [54.63510555 52.21388588]
 [33.91550011 98.86943574]
 

数据标准化，使用标准层

In [38]:
norm = Normalization(axis=-1)
norm.adapt(x)
x_n = norm(x)
print(x_n)

tf.Tensor(
[[-1.6022474   0.6383412 ]
 [-1.8262553  -1.2075416 ]
 [-1.5390396   0.36129424]
 [-0.28210124  1.0863684 ]
 [ 0.69152844  0.4933778 ]
 [-1.061997   -0.5357395 ]
 [-0.23437232  1.6381842 ]
 [ 0.48451123 -1.0637305 ]
 [ 0.53998667  1.146511  ]
 [ 0.97044855 -1.2270986 ]
 [ 1.5607548  -1.5141847 ]
 [ 0.48393863 -1.9264164 ]
 [ 0.8606503   0.5549035 ]
 [ 0.19215816  1.7034781 ]
 [-1.3483992   0.53082776]
 [-0.60293424  1.2431479 ]
 [ 0.17694996 -0.7291398 ]
 [ 0.11893079 -1.0569936 ]
 [ 0.2591455   1.4443302 ]
 [ 0.5854395  -1.008459  ]
 [ 0.08924025 -1.2646848 ]
 [ 1.2413042  -0.0228581 ]
 [-0.7804207  -0.9392391 ]
 [-1.6235069  -1.1905303 ]
 [ 0.6342659   0.14875136]
 [-0.17423227  0.20186768]
 [ 0.7513115  -1.1574253 ]
 [ 1.4188606  -1.4830649 ]
 [-0.19700044 -0.863505  ]
 [-1.3872683  -0.06632464]
 [-0.22029094  0.3561933 ]
 [ 1.0206376  -0.49595445]
 [-0.69916385 -0.16735731]
 [-0.7023958   0.17365736]
 [-1.3123181   0.26748756]
 [-0.5686351  -0.7576198 ]
 [-1.6388246   1.

拷贝数据，增加训练集的尺寸，从而减少训练的迭代次数

In [39]:
x_t = np.tile(x_n,(1000,1))
y_t = np.tile(y,(1000,1))
print(x_t.shape,y_t.shape)

(100000, 2) (100000, 1)


编译模型 model.compile()  
优化器optimizer：该参数可指定为已预定义的优化器名，如rmsprop、adagrad，或一个Optimizer类的对象，详情见optimizers  
损失函数loss：该参数为模型试图最小化的目标函数，它可为预定义的损失函数名，如categorical_crossentropy、mse，也可以为一个损失函数。详情见losses  
指标列表metrics：对分类问题，我们一般将该列表设置为metrics=['accuracy']。指标可以是一个预定义指标的名字,也可以是一个用户定制的函数.指标函数应该返回单个张量,或一个完成metric_name - > metric_value映射的字典.请参考性能评估  

In [40]:
model2.compile(optimizer="rmsprop",loss="binary_crossentropy",metrics=["accuracy"])

训练模型 model.fit()

In [41]:
model2.fit(x_t, y_t,epochs=100) #迭代100次，也可以加入batch_sized指定每次训练的数据个数

Epoch 1/100
3125/3125 ━━━━━━━━━━━━━━━━━━━━ 3s 737us/step - accuracy: 0.7144 - loss: 0.5323
Epoch 2/100
3125/3125 ━━━━━━━━━━━━━━━━━━━━ 2s 754us/step - accuracy: 0.8882 - loss: 0.2192
Epoch 3/100
3125/3125 ━━━━━━━━━━━━━━━━━━━━ 2s 726us/step - accuracy: 0.9014 - loss: 0.1836
Epoch 4/100
3125/3125 ━━━━━━━━━━━━━━━━━━━━ 2s 718us/step - accuracy: 0.9481 - loss: 0.1447
Epoch 5/100
3125/3125 ━━━━━━━━━━━━━━━━━━━━ 2s 703us/step - accuracy: 0.9549 - loss: 0.1188
Epoch 6/100
3125/3125 ━━━━━━━━━━━━━━━━━━━━ 2s 730us/step - accuracy: 0.9685 - loss: 0.0998
Epoch 7/100
3125/3125 ━━━━━━━━━━━━━━━━━━━━ 2s 717us/step - accuracy: 0.9991 - loss: 0.0831
Epoch 8/100
3125/3125 ━━━━━━━━━━━━━━━━━━━━ 2s 715us/step - accuracy: 0.9999 - loss: 0.0708
Epoch 9/100
3125/3125 ━━━━━━━━━━━━━━━━━━━━ 2s 720us/step - accuracy: 1.0000 - loss: 0.0600
Epoch 10/100
3125/3125 ━━━━━━━━━━━━━━━━━━━━ 2s 726us/step - accuracy: 1.0000 - loss: 0.0529
Epoch 11/100
3125/3125 ━━━━━━━━━━━━━━━━━━━━ 2s 733us/step - accuracy: 1.0000 - loss: 0.04

In [42]:
model2.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ L1 (Dense)                      │ (32, 3)                │             9 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ L2 (Dense)                      │ (32, 1)                │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 28 (116.00 B)

 Trainable params: 13 (52.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 15 (64.00 B)

预测新的输入

In [43]:
x_new = np.random.randint(30,90,(1000,2))
print(x_new)
# 预测的数据也需要标准化处理
x_new_t = norm(x_new)
print(x_new_t)
# 预测
pred = model2.predict(x_new_t)
print(pred)

[[42 87]
 [75 55]
 [44 40]
 ...
 [58 69]
 [51 86]
 [83 64]]
tf.Tensor(
[[-1.2212517   1.1237648 ]
 [ 0.48323327 -0.6069346 ]
 [-1.1179496  -1.4181999 ]
 ...
 [-0.39483473  0.15024634]
 [-0.7563921   1.0696803 ]
 [ 0.89644176 -0.12017544]], shape=(1000, 2), dtype=float32)
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
[[9.79130268e-01]
 [1.00000000e+00]
 [2.43494839e-33]
 [1.00000000e+00]
 [2.42682517e-33]
 [1.11875998e-07]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [8.92807384e-06]
 [9.34102251e-33]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.77092005e-07]
 [1.99865308e-32]
 [2.51791607e-06]
 [1.00000000e+00]
 [1.79255707e-07]
 [1.00000000e+00]
 [2.41673686e-33]
 [3.26015311e-07]
 [1.38473155e-07]
 [1.00000000e+00]
 [3.35252001e-24]
 [1.00000000e+00]
 [1.73106310e-32]
 [1.00000000e+00]
 [3.46630839e-33]
 [9.99943972e-01]
 [1.71438614e-07]
 [3.51402465e-33]
 [9.96903121e-01]
 [2.40485518e-33]
 [2.64694751e-03]
 [2.11571110e-03]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.84004156e-09]
 [1.

In [44]:
# 评估模型性能
loss, accuracy = model2.evaluate(x_t, y_t, verbose=2)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

3125/3125 - 2s - 664us/step - accuracy: 1.0000 - loss: 3.2586e-04
Test loss: 0.0003258591459598392
Test accuracy: 1.0


In [45]:
# 获取权重和偏置项
w_1,b_1 = model2.get_layer("L1").get_weights()
w_2,b_2 = model2.get_layer("L2").get_weights()
print(f"w_1 = {w_1},\tb_1 = {b_1}")
print(f"w_2 = {w_2},\tb_2 = {b_2}")

w_1 = [[ 3.3304431 -9.664695   2.9535916]
 [10.082937  -4.9125156  8.972853 ]],	b_1 = [ 9.064488  -5.7234864  7.9299803]
w_2 = [[ 33.972507]
 [-53.443333]
 [ 25.542484]],	b_2 = [-21.664501]
