In [1]:
import numpy as np

每一种array可以定义一种type，让其以小数，还是整数形式存在

使用dtype定义



In [2]:
a = np.array([2,23,4],dtype=int) # 默认int是32位
a1 = np.array([2,23,4],dtype=np.int64) # 输入np.int64可以将默认的32位int改为64位
print(a) # 输出可以看到没有逗号隔开
print(a.dtype) # 32位的int
print(a1)
print(a1.dtype)

[ 2 23  4]
int32
[ 2 23  4]
int64


In [3]:
b = np.array([[1,2,3],[4,5,6]],dtype=float)
b1 = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(b)
print(b.dtype) # 64位的float
print(b1)
print(b1.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
float64
[[1. 2. 3.]
 [4. 5. 6.]]
float32


全都为0的矩阵的定义 .zeros((行，列))

In [4]:
c = np.zeros((3,4)) # （3，4）为shape，代表3行4列
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


全是1的矩阵  .ones((行，列))

In [5]:
d = np.ones((3,4),dtype=np.int16)
print(d)
print(d.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int16


接近0的矩阵 .empty((行,列))

In [6]:
empty_zero = np.empty((2,6),dtype=np.float64)
print(empty_zero)
print(empty_zero.dtype)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
float64


指定范围 .arange(起始值,结束值，间隔)         不包含结束值

In [7]:
range_array = np.arange(10,20,3)
print(range_array)

[10 13 16 19]


使用.reshape((行，列)) 给一个1行多列的矩阵，变成目标的行列

In [8]:
rang_array1 = np.arange(8,20,1).reshape((3,4))
print(rang_array1)

[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


生成等间隔线段 .linspace(起始值，结束值，总段数)

In [ ]:
line_array = np.linspace(0,10,20,endpoint=True,retstep=True,dtype=np.float64)
print(line_array)
line_array1 = np.linspace(0,10,6).reshape((2,3))
print(line_array1)

(array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5]), 0.5)
[[ 0.  2.  4.]
 [ 6.  8. 10.]]
