numpy的基础运算

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
b = np.arange(4)
print(a,b)

[1 2 3 4] [0 1 2 3]


总结 简单的直接 + -可以完成矩阵的加减法，但是简单的直接 * / 不可以完成矩阵的乘除，只可以得到对应元素进行单独乘除

In [ ]:
c = a + b # 加法
print(c)
c1 = a - b # 减法
print(c1)
c2 = a * b # 乘法 只能对应位置元素相乘
print(c2)
c3 = a ** 2 # 对应元素求次方
print(c3)
c4 = b / a # 对应元素进行除法
print(c4)
c5 = 10 * np.sin(a) # 三角函数 .cos()  .tan() .arcsin() 等同理 注意是弧度制，需转换为角度
print(c5)
c6 = b % a # 对应元素求模
print(c6)
c7 = b // a # 对应元素向下取整
print(c7)
print(b < 3) # 显示小于3的值，以bool类型返回


[1 3 5 7]
[1 1 1 1]
[ 0  2  6 12]
[ 1  4  9 16]
[0.         0.5        0.66666667 0.75      ]
[ 8.41470985  9.09297427  1.41120008 -7.56802495]
[0 1 2 3]
[0 0 0 0]
[ True  True  True False]


In [ ]:
a = a.reshape((2,2))
b = b.reshape((2,2))
print(f"a = {a},b = {b}")
c = a * b
c_dot = np.dot(a,b) # 矩阵正确的乘法
c_dot2 = a.dot(b) # 另一种形式 numpy中所有的 np.函数(数组) 都可以定义为 数组.函数() 实现的功能一样
c_dot3 = b.dot(a) # 注意a*b和b*a的矩阵运算不一定相等
print(c)
print(c_dot)
print(c_dot2)
print(c_dot3)

a = [[1 2]
 [3 4]],b = [[0 1]
 [2 3]]
[[ 0  2]
 [ 6 12]]
[[ 4  7]
 [ 8 15]]
[[ 4  7]
 [ 8 15]]
[[ 3  4]
 [11 16]]


In [ ]:
import random
a = np.random.random((2,4)) # 随机生成的2行4列的0-1的随机矩阵
print(a)
print(np.sum(a)) # 求和
print(np.max(a)) # 最大值
print(np.min(a)) # 最小值
print(np.sum(a,axis = 1)) # 行求和
print(np.sum(a,axis = 0)) # 列求和
print(np.max(a,axis = 0)) # 列找最大值 其余同理

[[0.76673767 0.86613298 0.49015105 0.91667144]
 [0.62193535 0.82576708 0.8302648  0.0503718 ]]
5.368032188555133
0.9166714440542272
0.05037179963204863
[3.03969316 2.32833903]
[1.38867303 1.69190007 1.32041585 0.96704324]
[0.76673767 0.86613298 0.8302648  0.91667144]
