In [1]:
import numpy as np

In [2]:
A = np.arange(15,-1,-1).reshape((4,4))
print(A)

[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [7]:
print(np.argmin(A)) # 最小值索引 注意：第一位为0
print(np.argmax(A)) # 最大值索引
print(np.mean(A)) # 平均值 numpy中所有的 np.函数(数组) 都可以定义为 数组.函数() 实现的功能一样
print(np.average(A)) # 平均值，注意函数只可以np.average(数组) average支持加权平均值计算
print(np.median(A)) # 中位数
print(A.cumsum()) # 累加 元素i = i之前所有元素之和加原数组i位置元素
print(np.diff(A)) # 累差 每一行下一个元素与上一个元素的差值
print(np.nonzero(A)) # 显示非0的数的位置，输出每一个元素的行数和列数
print(np.sort(A)) # 每一行进行排序
print(np.transpose(A)) # 矩阵转置
print(A.T) # 同上T即为transpose()
print((A.T).dot(A))
print(np.clip(A,5,9)) # 滤波   即所有大于9的数变成9，小于5变成5

15
0
7.5
7.5
7.5
[ 15  29  42  54  65  75  84  92  99 105 110 114 117 119 120 120]
[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2], dtype=int64))
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[15 11  7  3]
 [14 10  6  2]
 [13  9  5  1]
 [12  8  4  0]]
[[15 11  7  3]
 [14 10  6  2]
 [13  9  5  1]
 [12  8  4  0]]
[[404 368 332 296]
 [368 336 304 272]
 [332 304 276 248]
 [296 272 248 224]]
[[9 9 9 9]
 [9 9 9 8]
 [7 6 5 5]
 [5 5 5 5]]


注意 上述这些求具体数值的函数都可以加axis = 0/1的实参，来进行行或者列的操作