In [15]:
import numpy as np

通过[]索引

In [16]:
A = np.arange(3,15)
print(A)
print(A[3])
A = A.reshape(3,4)
print(A)
print(A[0][3]) 
print(A[0,3])
print(A[1][2])
print(A[1,2])
print(A[2,:]) # ：代表行或列所有 
print(A[1,1:3]) # 切片

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
6
6
9
9
[11 12 13 14]
[8 9]


for循环

In [ ]:
for row in A: # 打印每一行
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [ ]:
for column in A.T: # 通过转置，然后迭代每一行，可以得到每列
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [ ]:
print(A.flatten()) # 返回只有一行多列的矩阵
for item in A.flat: # 返回每一个元素
    print(item) 

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14
