In [2]:
import numpy as np

通过.vstack()上下合并 .hstack()左右合并

In [ ]:
A = np.array([1,1,1])
B = np.array([2,2,2])
C = np.vstack((A,B)) # 上下合并
print(C)
print(A.shape,C.shape)
D = np.hstack((A,B)) # 左右合并
print(D)
print(np.shape(D))

[[1 1 1]
 [2 2 2]]
(3,) (2, 3)
[1 1 1 2 2 2]
(6,)
[1 1 1]


横向数列改纵向

In [ ]:
print(A.T.shape) # 发现转置一行，不可以得到转置后的一行多列
print(A)
print(A[:,np.newaxis])
print(A[:,np.newaxis].shape) # 通过.newaxis()加维度
print(A[np.newaxis,:])
print(A[np.newaxis,:].shape)

(3,)
[1 1 1]
[[1]
 [1]
 [1]]
(3, 1)
[[1 1 1]]
(1, 3)


In [16]:
A = A[:,np.newaxis]
B = B[:,np.newaxis]
C = np.hstack((A,B))
D = np.vstack((A,B))
print(C)
print(D)

[[[1]
  [2]]

 [[1]
  [2]]

 [[1]
  [2]]]
[[[1]]

 [[1]]

 [[1]]

 [[2]]

 [[2]]

 [[2]]]


In [19]:
C = np.concatenate((A,B,A,A,A),axis = 1) # 多个array合并，axis = 0/1可以控制在行还是列进行合并
print(C)

[[[1]
  [2]
  [1]
  [1]
  [1]]

 [[1]
  [2]
  [1]
  [1]
  [1]]

 [[1]
  [2]
  [1]
  [1]
  [1]]]
