In [2]:
import numpy as np

In [3]:
a = np.array([0,1,2,3])


= 进行赋值时，类似C++引用 指向同一块内存地址

In [4]:
b = a
c = a
d = b
a[0] = 11
print(a)
print(b)
print(c)
print(d)
print(b is a)
print(c is a)
print(d is a)
d[1:3] = [22,33]
print(a)
print(b)
print(c)
print(d)

[11  1  2  3]
[11  1  2  3]
[11  1  2  3]
[11  1  2  3]
True
True
True
[11 22 33  3]
[11 22 33  3]
[11 22 33  3]
[11 22 33  3]


.copy() 赋值，会得到另一个数组，这两个数组内存地址不同

In [5]:
b = np.copy(a)
print(b)
print(a is b)

[11 22 33  3]
False
